'use client'

import {
	AnnouncementBar,
	ArticleCard,
	AuthorBio,
	AuthPanel,
	BeforeAfter,
	BentoGrid,
	Breadcrumbs,
	Callout,
	Carousel,
	CollectionPage,
	CaseStudyCard,
	CheckList,
	Chips,
	ClientLogo,
	ComparisonTable,
	ContactSplit,
	Countdown,
	CtaBand,
	DetailCard,
	FaqAccordion,
	FeatureCard,
	FeatureRows,
	Figure,
	FilterBar,
	Grid,
	ImageCompare,
	LeadCapture,
	LogoStrip,
	Marquee,
	Masonry,
	MediaCard,
	MediaGallery,
	MediaMosaic,
	Notice,
	PageHero,
	Pagination,
	PricingTiers,
	ProcessSteps,
	ProseBlock,
	RelatedCard,
	RoiCalculator,
	SectionHeading,
	SplitCta,
	SplitHero,
	Spotlight,
	StatBand,
	StatHero,
	TableOfContents,
	TabsShowcase,
	TeamCard,
	TestimonialCard,
	VideoPlayer,
} from '@/components/sections'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnySection = React.ComponentType<any>

export const sectionRegistry: Record<string, AnySection> = {
	'page-hero': PageHero,
	'split-hero': SplitHero,
	'stat-hero': StatHero,
	'section-heading': SectionHeading,
	breadcrumbs: Breadcrumbs,
	'announcement-bar': AnnouncementBar,

	'stat-band': StatBand,
	'logo-strip': LogoStrip,
	spotlight: Spotlight,
	'before-after': BeforeAfter,

	'feature-rows': FeatureRows,
	'process-steps': ProcessSteps,
	'bento-grid': BentoGrid,
	'tabs-showcase': TabsShowcase,
	'comparison-table': ComparisonTable,
	chips: Chips,

	'faq-accordion': FaqAccordion,
	'contact-split': ContactSplit,
	'pricing-tiers': PricingTiers,
	'lead-capture': LeadCapture,
	'split-cta': SplitCta,
	'cta-band': CtaBand,

	'prose-block': ProseBlock,
	callout: Callout,
	'author-bio': AuthorBio,
	'check-list': CheckList,

	'video-player': VideoPlayer,
	'media-gallery': MediaGallery,
	'media-mosaic': MediaMosaic,
	'image-compare': ImageCompare,
	figure: Figure,

	'filter-bar': FilterBar,
	pagination: Pagination,
	'table-of-contents': TableOfContents,
	'roi-calculator': RoiCalculator,

	'detail-card': DetailCard,
	countdown: Countdown,
	'auth-panel': AuthPanel,
	notice: Notice,

	grid: Grid,
	masonry: Masonry,
	carousel: Carousel,
	marquee: Marquee,
	'collection-page': CollectionPage,

	'testimonial-card': TestimonialCard,
	'case-study-card': CaseStudyCard,
	'article-card': ArticleCard,
	'team-card': TeamCard,
	'related-card': RelatedCard,
	'feature-card': FeatureCard,
	'media-card': MediaCard,
	'client-logo': ClientLogo,
}

export function isKnownSection(type: string) {
	return type in sectionRegistry
}
